# Generated by Django 2.2.12 on 2020-10-10 14:54

from django.db import migrations, models
import rapid.models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=rapid.models.upload_to_cluster),
        ),
    ]
