# Generated by Django 2.2.12 on 2020-10-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='info',
            field=models.URLField(blank=True, help_text='URL for background info', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='metadata',
            field=models.URLField(blank=True, help_text='URL for metadata', null=True),
        ),
    ]
