version: '3'
services:
    db:
      image: postgres
      env_file: pg.env
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./initdb.d:/docker-entrypoint-initdb.d

    rapid:
      build: .
      env_file: django.env
      volumes:
        - .:/code
      command: python3 manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      depends_on:
        - db

